name: Build and Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        node: [ 20 ]
    runs-on: ubuntu-latest
    name: Astro Build for Node.js ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Configure npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Astro Build
        run: pnpm run build

      - name: Run Tests (if available)
        run: |
          if [ -f "package.json" ] && grep -q "\"test\":" package.json; then
            pnpm run test
          else
            echo "No test script found, skipping tests"
          fi
        continue-on-error: true

      - name: Run Type Check (if available)
        run: |
          if [ -f "package.json" ] && grep -q "\"type-check\":" package.json; then
            pnpm run type-check
          elif [ -f "tsconfig.json" ]; then
            pnpm tsc --noEmit
          else
            echo "No TypeScript configuration found, skipping type check"
          fi
        continue-on-error: true