name: Build and Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        node: [22, 23]
    runs-on: ubuntu-latest
    name: Astro Check for Node.js ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Astro Check
        uses: withastro/action@v3
        with:
          node-version: ${{ matrix.node }}
          package-manager: pnpm
          run: astro check

  build:
    strategy:
      matrix:
        node: [22, 23]
    runs-on: ubuntu-latest
    name: Astro Build for Node.js ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Astro Build
        uses: withastro/action@v3
        with:
          node-version: ${{ matrix.node }}
          package-manager: pnpm
          run: astro build
